var node_link_map,link_map,paper_map,node_map,node_in_neighbor_map,node_out_neighbor_map,link_rating_map,record_rating_map,selected_source,selected_target,active_data_nodes,active_data_links,active_data_nodes_force,active_data_links_force,svg_circular,svg_force,arcs,linkGenerator,links,force,vis_width=800,vis_height=800,inner_radius=0.32*Math.min(vis_width,vis_height),outer_radius=1.2*inner_radius,directionType={"in":1,out:2,bi:3},colorPalette=[d3.rgb(141,211,199).toString(),d3.rgb(255,255,179).toString(),
d3.rgb(190,186,218).toString(),d3.rgb(251,128,114).toString(),d3.rgb(128,177,211).toString(),d3.rgb(253,180,98).toString(),d3.rgb(179,222,105).toString(),d3.rgb(252,205,229).toString(),d3.rgb(217,217,217).toString(),d3.rgb(188,128,189).toString(),d3.rgb(204,235,197).toString(),d3.rgb(255,237,111).toString()],mutex=2,enable_piwik=!1;d3.json("media/data/test_node.json",function(b){node_map={};node_in_neighbor_map={};node_out_neighbor_map={};for(var a=b.length,d=0;d<a;++d){var c=b[d];c.circ={};node_map[c.key]=c;node_in_neighbor_map[c.key]=[];node_out_neighbor_map[c.key]=[]}mutex-=1});
d3.json("media/data/test_link.json",function(b){link_map={};node_link_map={};for(var a=b.length,d=0;d<a;++d){var c=b[d],f={key:c.key,source:node_map[c.sourceKey],target:node_map[c.targetKey]};link_map[f.key]=f;node_link_map[f.source.key+"-"+f.target.key]=f;node_in_neighbor_map[c.targetKey].push(c.sourceKey);node_out_neighbor_map[c.sourceKey].push(c.targetKey)}mutex-=1});waitForDataLoading();d3.select("#bt-search").on("click",searchButtonClick);d3.select("#bt-clear").on("click",clearButtonClick);$("#sourceSelect").change(sourceSearchInput);
$("#targetSelect").change(targetSearchInput);
function renderCanvas(){assignColors();initActiveNodes();computeCircularNodesParameters(active_data_nodes);initActiveLinks();arcs=d3.svg.arc().innerRadius(inner_radius).outerRadius(outer_radius).startAngle(function(a){return a.circ.startAngle}).endAngle(function(a){return a.circ.endAngle});force=d3.layout.force().nodes(active_data_nodes_force).links(active_data_links_force).size([vis_width,vis_height]).start();svg_circular=d3.select("#canvas-circular").append("svg").attr("width",vis_width).attr("height",
vis_height).append("g").attr("transform","translate("+vis_width/2+","+vis_height/2+")").append("g");svg_force=d3.select("#canvas-force").append("svg").attr("width",vis_width).attr("height",vis_height).append("g").append("g");enterCircularNodes(svg_circular);enterCircularLinks(svg_circular);var b=svg_force.selectAll("nodelink.links").data(active_data_links_force).enter().append("svg:line").attr("class","link").style("stroke-width",3),a=svg_force.selectAll("nodelink.nodes").data(active_data_nodes_force).enter().append("svg:circle").attr("class",
"node").attr("r",5).style("fill",function(a){return a.color}).call(force.drag);force.on("tick",function(){b.attr("x1",function(a){return a.source.x}).attr("y1",function(a){return a.source.y}).attr("x2",function(a){return a.target.x}).attr("y2",function(a){return a.target.y});a.attr("cx",function(a){return a.x}).attr("cy",function(a){return a.y})})}function setupUIElements(){appendNodesAsOptions(node_map);$(".chzn-select").chosen({allow_single_deselect:!0})}
function waitForDataLoading(){0<mutex?setTimeout(function(){waitForDataLoading()},1E3):(renderCanvas(),setupUIElements())};function expandRegion(b,a){console.log(a);var d=b.children,c=d.length;if(!(1>c)){for(var f=b.circ.startAngle,k=(b.circ.endAngle-f)/c,m=[],n=[],l=[],p=active_data_links.length,g=0;g<p;++g){var h=active_data_links[g];h.source===b&&(n.push(h.target),l.push(h.source.key+"-"+h.target.key));h.target===b&&(m.push(h.source),l.push(h.source.key+"-"+h.target.key))}for(var h=m.length,q=n.length,p=l.length,g=0;g<c;++g){var j=node_map[d[g]];calculateArcPositions(j,f,k,g);j.color=b.color;active_data_nodes.push(j);
for(var i=0;i<h;++i){var e=m[i],e=e.key+"-"+j.key,e=node_link_map[e];void 0!==e&&active_data_links.push(e)}for(i=0;i<q;++i)e=n[i],e=j.key+"-"+e.key,e=node_link_map[e],void 0!==e&&active_data_links.push(e)}enterCircularNodes(a);enterCircularLinks(a);d=$.inArray(b,active_data_nodes);active_data_nodes.splice(d,1);for(g=0;g<p;++g)e=l[g],e=node_link_map[e],console.log(e),d=$.inArray(e,active_data_links),console.log(d),active_data_links.splice(d,1);a.selectAll("path").data(active_data_nodes,function(a){return a.key}).exit().remove();
a.selectAll("text").data(active_data_nodes,function(a){return a.key}).exit().remove();a.selectAll("line").data(active_data_links,function(a){return a.key}).exit().remove();console.log(active_data_links)}}function linkClick(){}
function enterCircularNodes(b){b.selectAll("circular.nodes").data(active_data_nodes,function(a){return a.key}).enter().append("svg:path").style("fill",function(a){return a.color}).style("stroke","gray").attr("d",arcs).on("click",function(a){expandRegion(a,b)});b.selectAll("text").data(active_data_nodes,function(a){return a.key}).enter().append("text").attr("x",function(a){return a.circ.x}).attr("y",function(a){return a.circ.y}).attr("class","text visible").text(function(a){return a.name})}
function enterCircularLinks(b){b.selectAll("circular.links").data(active_data_links,function(a){return a.key}).enter().append("svg:line").attr("stroke","black").attr("fill","none").attr("x1",function(a){return a.source.circ.x}).attr("x2",function(a){return a.target.circ.x}).attr("y1",function(a){return a.source.circ.y}).attr("y2",function(a){return a.target.circ.y}).on("click",linkClick)}
function highlightNode(b,a,d,c,f){void 0===b?console.log("undefined node in highlightNode"):(f.select("#arc-"+b.key).classed(a,d),c&&f.select("#text-"+b.key).classed("selected",d))}function expandNode(){}function expandLink(){};function appendNodesAsOptions(b){console.log(b);for(var a in b){var d=b[a];$("#sourceSelect").append(new Option(d.name,d.name,!1,!1));$("#targetSelect").append(new Option(d.name,d.name,!1,!1))}}function searchButtonClick(){}function clearButtonClick(){}function sourceSearchInput(){enable_piwik&&piwikTracker.trackPageView("Set source for search")}function targetSearchInput(){}function clearSearchResult(){};function contains(b,a){for(var d=b.length,c=0;c<d;++c)if(a.key===b[c].key)return c;return-1}function initActiveNodes(){active_data_nodes=[];active_data_nodes_force=[];for(var b in node_map){var a=node_map[b];1===a.depth&&active_data_nodes.push(a);var d=0,d=d+node_in_neighbor_map[b].length,d=d+node_out_neighbor_map[b].length;2===a.depth&&0<d&&active_data_nodes_force.push(a)}active_data_nodes_force[0].isSource=!0;active_data_nodes_force[1].isTarget=!0}
function initActiveLinks(){active_data_links=[];active_data_links_force=[];for(var b in link_map){var a=link_map[b];1===a.source.depth&&1===a.target.depth&&active_data_links.push(a);2===a.source.depth&&2===a.target.depth&&active_data_links_force.push(a)}}
function assignColors(){var b=0,a=[],d;for(d in node_map){var c=node_map[d];1===c.depth&&(b+=1,a.push(c))}d=[];for(c=0;c<b;++c)d.push(colorPalette[c]);d3.scale.ordinal().domain(d3.range(b)).range(d);for(c=0;c<b;++c){a[c].color=d[c];for(var f=0;f<a[c].children.length;++f){var k=node_map[a[c].children[f]];k.color=d[c];k.group=a[c].key}}}function computeCircularNodesParameters(b){for(var a=b.length,d=2*Math.PI/a,c=0;c<a;++c)calculateArcPositions(b[c],0,d,c)}
function calculateArcPositions(b,a,d,c){b.circ.startAngle=a+d*c;b.circ.endAngle=a+d*(c+1);a=d*(c+0.5)+a;d=inner_radius+(outer_radius-inner_radius)/2;b.circ.x=d*Math.cos(Math.PI/2-a);b.circ.y=-d*Math.sin(Math.PI/2-a)};
