var node_link_map,link_map,paper_map,node_map,node_in_neighbor_map,node_out_neighbor_map,link_rating_map,record_rating_map,selected_source,selected_target,active_data_nodes,active_data_links,active_data_nodes_force,active_data_links_force,svg_circular,svg_force,arcs,linkGenerator,links,force,vis_width=800,vis_height=800,inner_radius=0.32*Math.min(vis_width,vis_height),outer_radius=1.2*inner_radius,directionType={"in":1,out:2,bi:3},colorPalette=[d3.rgb(141,211,199).toString(),d3.rgb(255,255,179).toString(),
d3.rgb(190,186,218).toString(),d3.rgb(251,128,114).toString(),d3.rgb(128,177,211).toString(),d3.rgb(253,180,98).toString(),d3.rgb(179,222,105).toString(),d3.rgb(252,205,229).toString(),d3.rgb(217,217,217).toString(),d3.rgb(188,128,189).toString(),d3.rgb(204,235,197).toString(),d3.rgb(255,237,111).toString()],mutex=2,enable_piwik=!1;d3.json("media/data/test_node.json",function(c){node_map={};node_in_neighbor_map={};node_out_neighbor_map={};for(var b=c.length,a=0;a<b;++a){var d=c[a];d.circ={};node_map[d.key]=d;node_in_neighbor_map[d.key]=[];node_out_neighbor_map[d.key]=[]}for(var e in node_map){d=node_map[e];for(a=0;a<d.children.length;++a)c=node_map[d.children[a]],void 0!==c&&(c.parent=e,c.group=e)}mutex-=1});
d3.json("media/data/test_link.json",function(c){link_map={};node_link_map={};for(var b=c.length,a=0;a<b;++a){var d=c[a],e={key:d.key,source:node_map[d.sourceKey],target:node_map[d.targetKey]};link_map[e.key]=e;node_link_map[e.source.key+"-"+e.target.key]=e;node_in_neighbor_map[d.targetKey].push(d.sourceKey);node_out_neighbor_map[d.sourceKey].push(d.targetKey)}mutex-=1});waitForDataLoading();d3.select("#bt-search").on("click",searchButtonClick);d3.select("#bt-clear").on("click",clearButtonClick);$("#sourceSelect").change(sourceSearchInput);
$("#targetSelect").change(targetSearchInput);
function renderCanvas(){assignColors();initActiveNodes();computeCircularNodesParameters(active_data_nodes);initActiveLinks();arcs=d3.svg.arc().innerRadius(inner_radius).outerRadius(outer_radius).startAngle(function(a){return a.circ.startAngle}).endAngle(function(a){return a.circ.endAngle});force=d3.layout.force().nodes(active_data_nodes_force).links(active_data_links_force).size([vis_width,vis_height]).start();svg_circular=d3.select("#canvas-circular").append("svg").attr("width",vis_width).attr("height",
vis_height).append("g").attr("transform","translate("+vis_width/2+","+vis_height/2+")").append("g");svg_force=d3.select("#canvas-force").append("svg").attr("width",vis_width).attr("height",vis_height).append("g").append("g");enterCircularNodes(svg_circular);enterCircularLinks(svg_circular);var c=svg_force.selectAll("nodelink.links").data(active_data_links_force).enter().append("svg:line").attr("class","link").style("stroke-width",3),b=svg_force.selectAll("nodelink.nodes").data(active_data_nodes_force).enter().append("svg:circle").attr("class",
"node").attr("r",5).style("fill",function(a){return a.color}).call(force.drag);force.on("tick",function(){c.attr("x1",function(a){return a.source.x}).attr("y1",function(a){return a.source.y}).attr("x2",function(a){return a.target.x}).attr("y2",function(a){return a.target.y});b.attr("cx",function(a){return a.x}).attr("cy",function(a){return a.y})})}function setupUIElements(){appendNodesAsOptions(node_map);$(".chzn-select").chosen({allow_single_deselect:!0})}
function waitForDataLoading(){0<mutex?setTimeout(function(){waitForDataLoading()},1E3):(renderCanvas(),setupUIElements())};function expandRegion(c,b){console.log(b);var a=c.children,d=a.length;if(!(1>d)){for(var e=c.circ.startAngle,p=(c.circ.endAngle-e)/d,l=[],m=[],k=[],n=active_data_links.length,g=0;g<n;++g){var h=active_data_links[g];h.source===c&&(m.push(h.target),k.push(h.source.key+"-"+h.target.key));h.target===c&&(l.push(h.source),k.push(h.source.key+"-"+h.target.key))}for(var h=l.length,q=m.length,n=k.length,g=0;g<d;++g){var j=node_map[a[g]];calculateArcPositions(j,e,p,g);j.color=c.color;active_data_nodes.push(j);
for(var i=0;i<h;++i){var f=l[i],f=f.key+"-"+j.key,f=node_link_map[f];void 0!==f&&active_data_links.push(f)}for(i=0;i<q;++i)f=m[i],f=j.key+"-"+f.key,f=node_link_map[f],void 0!==f&&active_data_links.push(f)}enterCircularNodes(b);enterCircularLinks(b);a=$.inArray(c,active_data_nodes);active_data_nodes.splice(a,1);for(g=0;g<n;++g)f=k[g],f=node_link_map[f],console.log(f),a=$.inArray(f,active_data_links),console.log(a),active_data_links.splice(a,1);b.selectAll("path").data(active_data_nodes,function(a){return a.key}).exit().remove();
b.selectAll("text").data(active_data_nodes,function(a){return a.key}).exit().remove();b.selectAll("line").data(active_data_links,function(a){return a.key}).exit().remove();console.log(active_data_links)}}function linkClick(){}
function enterCircularNodes(c){c.selectAll("circular.nodes").data(active_data_nodes,function(b){return b.key}).enter().append("svg:path").style("fill",function(b){return b.color}).style("stroke","gray").attr("d",arcs).on("click",function(b){expandRegion(b,c)});c.selectAll("text").data(active_data_nodes,function(b){return b.key}).enter().append("text").attr("x",function(b){return b.circ.x}).attr("y",function(b){return b.circ.y}).attr("class","text visible").text(function(b){return b.name})}
function enterCircularLinks(c){c.selectAll("circular.links").data(active_data_links,function(b){return b.key}).enter().append("svg:line").attr("stroke","black").attr("fill","none").attr("x1",function(b){return b.source.circ.x}).attr("x2",function(b){return b.target.circ.x}).attr("y1",function(b){return b.source.circ.y}).attr("y2",function(b){return b.target.circ.y}).on("click",linkClick)}
function highlightNode(c,b,a,d,e){void 0===c?console.log("undefined node in highlightNode"):(e.select("#arc-"+c.key).classed(b,a),d&&e.select("#text-"+c.key).classed("selected",a))}function expandNode(){}function expandLink(){};function appendNodesAsOptions(c){console.log(c);for(var b in c){var a=c[b];$("#sourceSelect").append(new Option(a.name,a.name,!1,!1));$("#targetSelect").append(new Option(a.name,a.name,!1,!1))}}function searchButtonClick(){}function clearButtonClick(){}function sourceSearchInput(){enable_piwik&&piwikTracker.trackPageView("Set source for search")}function targetSearchInput(){}function clearSearchResult(){};function contains(c,b){for(var a=c.length,d=0;d<a;++d)if(b.key===c[d].key)return d;return-1}function initActiveNodes(){active_data_nodes=[];active_data_nodes_force=[];for(var c in node_map){var b=node_map[c];1===b.depth&&active_data_nodes.push(b);var a=0,a=a+node_in_neighbor_map[c].length,a=a+node_out_neighbor_map[c].length;2===b.depth&&0<a&&active_data_nodes_force.push(b)}active_data_nodes_force[0].isSource=!0;active_data_nodes_force[1].isTarget=!0}
function initActiveLinks(){active_data_links=[];active_data_links_force=[];for(var c in link_map){var b=link_map[c];1===b.source.depth&&1===b.target.depth&&active_data_links.push(b);2===b.source.depth&&2===b.target.depth&&active_data_links_force.push(b)}}
function assignColors(){var c=0,b=[],a;for(a in node_map){var d=node_map[a];1===d.depth&&(c+=1,b.push(d))}a=[];for(d=0;d<c;++d)a.push(colorPalette[d]);d3.scale.ordinal().domain(d3.range(c)).range(a);for(d=0;d<c;++d){b[d].color=a[d];for(var e=0;e<b[d].children.length;++e)node_map[b[d].children[e]].color=a[d]}}function computeCircularNodesParameters(c){for(var b=c.length,a=2*Math.PI/b,d=0;d<b;++d)calculateArcPositions(c[d],0,a,d)}
function calculateArcPositions(c,b,a,d){c.circ.startAngle=b+a*d;c.circ.endAngle=b+a*(d+1);b=a*(d+0.5)+b;a=inner_radius+(outer_radius-inner_radius)/2;c.circ.x=a*Math.cos(Math.PI/2-b);c.circ.y=-a*Math.sin(Math.PI/2-b)};
